### ISSUE TITLE
get object in lower level of bucket

### ISSUE THREAD

**Issue by jingpengwu** [joshbode/GoogleCloud.jl#1]
Thanks for making this great package, the code organization is pretty clear!

storing files directly in bucket works fine, but when I tried to get file in the lower level (eg. `gs://bkt/key.h5` works, but `gs://bkt/folder/key.h5` do not), it returned a dict:

```
Dict{Symbol,Any} with 1 entry:
  :error => Dict{Symbol,Any}(Pair{Symbol,Any}(:code,404),Pair{Symbol,Any}(:message,"Not Found"))
```

to reproduce, just replace the `image.jpg` to `test/image.jpg` in the tutorial.

```
# Upload
storage(:Object, :insert, "a12345foo";     # Returns metadata about the object
    name="test/image.jpg",           # Object name is "image.jpg"
    data=file_contents,         # The data being stored on your project
    content_type="image/jpeg"   # The contents are specified to be in JPEG format
)
```

**Comment by joshbode** [comment]
Thanks! Looks like the query parameters (basically any unconsumed keyword arguments) _are_ getting URI encoded. However, I'm not encoding the path parameters (which you can see by adding `debug=true` to the keyword arguments). I'll fix that and try to get a release tagged (I've got some other improvements in master such as gzipping. In the meantime, if you use `:get` with `URIParser.escape("test/image.jpg")` instead, it should work.

**Comment by joshbode** [comment]
`master` has the fix now if you want to try :)

**Comment by jingpengwu** [comment]
tested, it works, thanks a lot!

**Comment by jingpengwu** [comment]
also, is there a direct way to list all the files in a lower level "directory"?
If Google Cloud Storage can only respond with all the keys, I have to filter them out locally?

**Comment by joshbode** [comment]
According to the Google Storage docs for the [list](https://cloud.google.com/storage/docs/json_api/v1/objects/list) method, there is a parameter called `prefix` which works for this.

```julia
storage(:Object, :list, "bucket_name"; prefix="subdir/subsubdir/", debug=true)
```

**Comment by joshbode** [comment]
BTW, escaping should no longer be necessary after d5de1ac

**Comment by joshbode** [comment]
You may also be interested in the `delimiter` parameter in the API docs

**Comment by jingpengwu** [comment]
@joshbode thanks, this is very helpful, so I can always refer to the google cloud documentation for the usage of this package?

**Comment by joshbode** [comment]
You're welcome :)

Generally, yes - unbound keyword parameters are passed through to the REST call as query parameters, so hopefully it Just Works :tm:

**Comment by jingpengwu** [comment]
thanks again, I think we can close this issue for now.
