### ISSUE TITLE
how to figure out the usage method?

### ISSUE THREAD

**Issue by jingpengwu** [joshbode/GoogleCloud.jl#11]
I am playing with the `logging` api, and can not find a correct way to use it!

I am looking at the RESTful API documentation, but can not figure out the correspondence with this package..

Here is an example, the project metric can not be created due to format error.
```julia
using GoogleCloud
creds = GoogleCredentials(expanduser("my_credentials.json"))
session = GoogleSession(creds, ["logging.write"])

set_session!(logging, session)

logging(:ProjectMetric, :create, "testMetric")
```

another existing example is the storage. the usage keyword do not match the google rest api documentation: 
https://cloud.google.com/storage/docs/json_api/v1/objects/insert

```julia
# Upload
storage(:Object, :insert, "a12345foo";     # Returns metadata about the object
    name="image.jpg",           # Object name is "image.jpg"
    data=file_contents,         # The data being stored on your project
    content_type="image/jpeg"   # The contents are specified to be in JPEG format
)
```
where does the `name`, `data`, and `content_type` come from?

@joshbode could you please give a hint to find the correct way to use the apis?

**Comment by joshbode** [comment]
I added the logging API, but never ended up using it so I don't have much experience with that one, sorry. I'll take a look, though. What is the format error?

I've generally tried to stay pretty close to the published API, with only a few exceptions.

The `name` argument _is_ one of the Storage API optional query parameters (from [insert](https://cloud.google.com/storage/docs/json_api/v1/objects/insert)):

> Name of the object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any. For information about how to URL encode object names to be path safe, see Encoding URI Path Parts. 

The `data` argument is _not_ named in the API, but corresponds always to the body of the request (I chose `data` since it matches the same argument in `Requests.jl`)

The `content_type` argument is also not in the API directly, but maps to the `Content-Type` HTTP header.

BTW, I'm actually developing a logger (with metrics) of my own that I'm releasing soon, which logs to console, file, datastore (or any API, really - it is extendable via an abstract type/registration method and configurable from YAML). It also includes methods of retrieving/parsing logs in addition to writing them.

**Comment by joshbode** [comment]
In the API, URL parameters match to positional arguments, e.g.
````
https://api_root/collection/{x}/{y}/method -> api(:collection, :method, x, y; ...)
````
where collection names are made singular and renamed slightly if they contain non-identifier characters (e.g. project.metrics -> ProjectMetric).

So, looking at [projects.metrics/create](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics/create) we need the project name as a positional argument, and the body needs to be an "instance" of [`LogMetric`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.metrics#LogMetric)

Which leads to:
```julia
logging(:ProjectMetric, :create, "your-project-000000"; data=Dict(:name => "test", :description => "Test metric", :filter => "resource.type = gae_app AND severity >= ERROR"))
```

**Comment by joshbode** [comment]
Ideally we'd be consuming the metadata for the individual APIs from the Google Discovery API and building out the Julia API dynamically (perhaps performed at precompile time or when explicitly requested to speed load time)

e.g.
https://www.googleapis.com/discovery/v1/apis/storage/v1/rest?fields=resources(buckets(methods(insert)))
```
{
 "resources": {
  "buckets": {
   "methods": {
    "insert": {
     "id": "storage.buckets.insert",
     "path": "b",
     "httpMethod": "POST",
     "description": "Creates a new bucket.",
     "parameters": {
      "predefinedAcl": {
       "type": "string",
       "description": "Apply a predefined set of access controls to this bucket.",
       "enum": [
        "authenticatedRead",
        "private",
        "projectPrivate",
        "publicRead",
        "publicReadWrite"
       ],
       "enumDescriptions": [
        "Project team owners get OWNER access, and allAuthenticatedUsers get READER access.",
        "Project team owners get OWNER access.",
        "Project team members get access according to their roles.",
        "Project team owners get OWNER access, and allUsers get READER access.",
        "Project team owners get OWNER access, and allUsers get WRITER access."
       ],
       "location": "query"
      },
      "predefinedDefaultObjectAcl": {
       "type": "string",
       "description": "Apply a predefined set of default object access controls to this bucket.",
       "enum": [
        "authenticatedRead",
        "bucketOwnerFullControl",
        "bucketOwnerRead",
        "private",
        "projectPrivate",
        "publicRead"
       ],
       "enumDescriptions": [
        "Object owner gets OWNER access, and allAuthenticatedUsers get READER access.",
        "Object owner gets OWNER access, and project team owners get OWNER access.",
        "Object owner gets OWNER access, and project team owners get READER access.",
        "Object owner gets OWNER access.",
        "Object owner gets OWNER access, and project team members get access according to their roles.",
        "Object owner gets OWNER access, and allUsers get READER access."
       ],
       "location": "query"
      },
      "project": {
       "type": "string",
       "description": "A valid API project identifier.",
       "required": true,
       "location": "query"
      },
      "projection": {
       "type": "string",
       "description": "Set of properties to return. Defaults to noAcl, unless the bucket resource specifies acl or defaultObjectAcl properties, when it defaults to full.",
       "enum": [
        "full",
        "noAcl"
       ],
       "enumDescriptions": [
        "Include all properties.",
        "Omit owner, acl and defaultObjectAcl properties."
       ],
       "location": "query"
      }
     },
     "parameterOrder": [
      "project"
     ],
     "request": {
      "$ref": "Bucket"
     },
     "response": {
      "$ref": "Bucket"
     },
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.full_control",
      "https://www.googleapis.com/auth/devstorage.read_write"
     ]
    }
   }
  }
 }
}
```
https://www.googleapis.com/discovery/v1/apis/storage/v1/rest?fields=auth(oauth2(scopes))
```
{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud-platform.read-only": {
     "description": "View your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/devstorage.full_control": {
     "description": "Manage your data and permissions in Google Cloud Storage"
    },
    "https://www.googleapis.com/auth/devstorage.read_only": {
     "description": "View your data in Google Cloud Storage"
    },
    "https://www.googleapis.com/auth/devstorage.read_write": {
     "description": "Manage your data in Google Cloud Storage"
    }
   }
  }
 }
}
```

**Comment by joshbode** [comment]
Did this help? Can I close this issue?

**Comment by jingpengwu** [comment]
sorry, I did not got a chance to try! Actually, I am moving to python for cloud stuff!

**Comment by joshbode** [comment]
Fair enough - Python support for this kind of thing is very mature :)
