### ISSUE TITLE
KeyStore can only store stuff in a bucket?

### ISSUE THREAD

**Issue by jingpengwu** [joshbode/GoogleCloud.jl#4]
there is only a bucket name in the constructor. 

https://github.com/joshbode/GoogleCloud.jl/blob/master/src/collection.jl#L24

can we make a subdirectory as a keystore, such as `gs://bucketname/keystorename/`

**Comment by joshbode** [comment]
Google Storage buckets use a flat namespace (see the [storage faq](https://cloud.google.com/storage/docs/faq)) with no true directory structure, so you can specify it via the key, e.g.
```julia
store = KeyStore{String, String}("bucketname.example.com")
store["keystorename/foo"] = "123"
```

BTW, pull on master again - I just committed a quick fix :)

**Comment by jingpengwu** [comment]
great, Thanks 👍
