### ISSUE TITLE
KeyStore constructor documentation 

### ISSUE THREAD

**Issue by jingpengwu** [joshbode/GoogleCloud.jl#5]
In the KeyStore documentation, there is a `reset` parameter, but is absent in the code. It should be replaced with `empty`?

https://github.com/joshbode/GoogleCloud.jl/blob/master/src/collection.jl#L25

**Comment by joshbode** [comment]
That's right - `empty` will clear out an existing bucket when the `KeyStore` "connection" is established (and do nothing on a new bucket).

Sorry, this underwent a fair bit of change over the last month or so and we need to update the documentation.
